### ISSUE TITLE
Please, add example with callback writing data to passed buffer

### ISSUE THREAD

**Issue by olekhov** [Michael-F-Bryan/rust-closures-and-ffi#1]
Hello, Michael.
Very nice FFI howto.
I am new to Rust, just learning. Not all things here are easy to understand.
I can't figure how to apply these examples to my case.
Consider this C library interface:
```
typedef int (*store_callback)(char *str, void *cb_ctx);
int func(void* lib_ctx, store_callback cb, void *cb_ctx);
```

When I call a library `func` method, it calls supplied callback and expects
that some data will be stored at `str`. `str` is allocated by library
and is enough to store say 16 bytes. `cb` callback should not write more than
16 bytes to that location. `cb_ctx` is passed to callback when it is invoked.
If callback returns 0, `func` can procede. Otherwise `func` returns 
something like "callback failed" error code.

This is very similar to curl `OnDataReceived` callback, but data is passed
in other direction. 

I can't figure out how to implement your approach in this case.

**Comment by Michael-F-Bryan** [comment]
I don't think this is specific to closures, so it's probably out of scope for the blog post. Your problem is knowing how to convert C arguments to something more idiomatic to Rust, in this case accessing the buffer as `&mut [u8]` instead of `&[u8]`.

---

First, I'd create declarations for `store_callback` and `func`, plus your assumed maximum buffer size of 16.

```rust
type StoreCallback = unsafe extern "C" fn(buffer: *mut c_char, ctx: *mut c_void) -> c_int;

const MAX_BUFFER_LEN: usize = 16;

extern "C" {
    fn func(lib_ctx: *mut c_void, callback: StoreCallback, callback_ctx: *mut c_void) -> c_int;
}
```

If you were using a callback in Rust that writes to some buffer its function signature would probably be something like `fn(buffer: &mut [u8]) -> std::io::Result<()>`. Now we need to convert the arguments passed to `StoreCallback` (ignoring `ctx`, because that's a pointer to our closure) into the arguments required by the Rust function.

In this case the caller has passed us a pointer to some buffer, and we already know the buffer is at least 16 elements long. This is exactly the job for [`std::slice::from_raw_parts_mut()`](https://doc.rust-lang.org/std/slice/fn.from_raw_parts_mut.html).

Next we define some trampoline function which satisfies the `StoreCallback` signature, converts our arguments, and invokes the closure.

```rust
unsafe extern "C" fn trampoline<F>(buffer: *mut c_char, ctx: *mut c_void) -> c_int
where
    F: FnMut(&mut [u8]) -> c_int,
{
    // Safety: We know the context is a pointer to our closure because `trampoline` is
    // private and the only way you can create one is via a publicly defined getter
    let closure = &mut *(ctx as *mut F);

    // Convert the buffer to a Rust slice.
    //
    // Safety: The caller didn't pass in the buffer size, so it *must* have
    // allocated at least MAX_BUFFER_LEN bytes
    let buffer = std::slice::from_raw_parts_mut(buffer as *mut u8, MAX_BUFFER_LEN);

    // actually invoke our closure
    closure(buffer)
}
```

For convenience (because a closure's type is unnameable) we'll create a helper function which creates a `trampoline` specific to our closure.

```rust
fn get_callback<F>(_closure: &F) -> StoreCallback
where
    F: FnMut(&mut [u8]) -> c_int,
{
    // ask the compiler to generate a "trampoline" specific to our closure, F
    trampoline::<F>
}
```

(Note: at this point I don't know what your error policy is, so we'll make the user return a `c_int` instead letting the trampoline convert a `std::io::Result<()>`  into `c_int` for them)

And that's pretty much it. Now you just need to use the code:

```rust
fn main() {
    unsafe {
        let mut write_to_buffer = |mut buffer: &mut [u8]| {
            match write!(buffer, "Hello, World!") {
                // I'm not sure what your error convention is, so I'll just
                // return 1 for success and 0 for failure
                Ok(_) => 1,
                Err(_) => 0,
            }
        };

        // get a function that can be used as a callback
        let callback = get_callback(&write_to_buffer);

        // you'll get this from somewhere else
        let lib_ctx = ptr::null_mut();

        let return_code = func(
            lib_ctx,
            callback,
            &mut write_to_buffer as *mut _ as *mut c_void,
        );

        assert_eq!(return_code, 1);
    }
}
```

I've also written this up on [the playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6bfc10c1815daaf61aa4b974f6845b00) so you can poke around and experiment yourself.

@olekhov, does that help answer your question? If not, let me know and I can re-open the issue.

**Comment by olekhov** [comment]
👍👍
Thanks a lot!
my working example: https://github.com/olekhov/rust-ffi-closure
